dat <- read.csv("HW_3_R.csv")
row <- subset(dat, TransactionAmount == max(TransactionAmount))
subset_1 <- subset(dat,DonorNameNormalized=="California Hospitals Committee on Issues, (CHCI) Sponsored by California Association of Hospitals and Health Systems (CAHHS)")
total_contri <- sum(row$TransactionAmount)
set_avg <- mean(subset(dat, TransactionAmount>0)$TransactionAmount)
row_2 <- subset(dat, TransactionAmount>0)
support_avg <- mean(subset(row_2,Position=='SUPPORT')$TransactionAmount)
oppose_avg <- mean(subset(row_2,Position=='OPPOSE')$TransactionAmount)
individual_type = subset(dat, DonorEntityType == 'IND')
individual_max = subset(individual_type, TransactionAmount == max(TransactionAmount))$TransactionAmount
table_freq = as.data.frame(table(unlist(dat$DonorCity)))
city_row = subset(table_freq, Freq == max(Freq))
sacramento = subset(dat, DonorCity == 'Sacramento')
percentage = city_row$Freq/sum(table_freq$Freq)*100
table_freq_sac = as.data.frame(table(unlist(sacramento$DonorOccupationNormalized)))
city_row_occu = subset(table_freq_sac, Freq == max(Freq))
head(table_freq_sac[order( table_freq_sac[,2],decreasing=TRUE),])
percentage2 = head(table_freq_sac[order( table_freq_sac[,2],decreasing=TRUE),])[2,]$Freq/sum(table_freq_sac$Freq)*100
support_frame = subset(sacramento,Position=='SUPPORT')
oppose_frame = subset(sacramento,Position=='OPPOSE')
table_freq_sac_support = as.data.frame(table(unlist(support_frame$Target)))
table_freq_sac_oppose = as.data.frame(table(unlist(oppose_frame$Target)))
head(table_freq_sac_support[order( table_freq_sac_support[,2],decreasing=TRUE),])
head(table_freq_sac_oppose[order( table_freq_sac_oppose[,2],decreasing=TRUE),])